
# Включаем роль центрального устройства (для донгла)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# ГЛАВНОЕ: Включаем поддержку matrix transform
# CONFIG_ZMK_MATRIX_TRANSFORM=y
